### ISSUE TITLE
EPIC - Sprint 2: Create a ShoppingCart RESTful service

### ISSUE THREAD

**Issue by aknain12** [devopsfantasticfour/shopcarts#15]
**As a** user of the e-commerce application
**I need** ...  to be able to
access the shopping-cart piece of the application

**So that** ...  I can
- Add an item to the cart
  with following parameters: Product, Quantity, Price, Time
- Delete an item from cart
- Modify quantity of an item
- Get (show) all the items in the shopping cart
   {Item 1 with details, Item 2 with details, SubTotal}
- Proceed with checkout to pay

**Assumptions:** 
Cannot delete the shopping cart
Can only empty the cart
Item to be added would come from the Product List

**Acceptance Criteria:**
Given 
The user has access to the shopping cart

When the user:

1. Adds an item to the shopping cart
2. Delete an item from the shopping cart
3. Modify an item in the shopping cart
4. View the items in the shopping cart

Then ...

1. Item would be added to the user' shopping cart
2. Item would be deleted from the shopping cart
3. Item would be modified in the shopping cart
4. Items details (Product Name, Price, Quantity) & Subtotal is sent to the presentation layer

**Comment by am7330** [comment]
Changed : I changed the title to make it clear it was an epic
