### ISSUE TITLE
Andrea: Learn about RESTful APIs

### ISSUE THREAD

**Issue by ag5493** [devopsfantasticfour/shopcarts#17]
**As a** RESTful API development team member
**I need** to understand the basics of RESTful interface
**So that** I can communicate with other RESTful developers

**Assumptions:** 
* Access to REST documentation 

**Acceptance Criteria:**
- Can answer what is CRUD?
- Skim through https://www.ics.uci.edu/~fielding/pubs/dissertation/fielding_dissertation.pdf 

Given 
- A RESTful conversation
When 
- developers communicate
Then 
- I can add value to the conversation

**Comment by am7330** [comment]
http://blog.vulk.coop/breaking-down-the-rest-dissertation-part-1-overview/ is a great summary!

**Comment by am7330** [comment]
And for a high-level understanding (for non- technical profile, the Wikipedia is actually an interesting tool: https://en.wikipedia.org/wiki/Representational_state_transfer
