### ISSUE TITLE
David: Learn about RESTful APIs

### ISSUE THREAD

**Issue by ag5493** [devopsfantasticfour/shopcarts#18]
**As a** RESTful API development team member 
**I need** to understand the basics of RESTful interface 
**So that** I can communicate with other RESTful developers  

**Assumptions:**  
* Access to REST documentation  

**Acceptance Criteria:** 
- Can answer what is CRUD? 
- Skim through https://www.ics.uci.edu/~fielding/pubs/dissertation/fielding_dissertation.pdf   

Given 
 - A RESTful conversation 
When  
- developers communicate 
Then  
- I can add value to the conversation

**Comment by newgreg** [comment]
Didn't read the whole thing... but read up on restful
