### ISSUE TITLE
Amit: Install Mozilla Extension

### ISSUE THREAD

**Issue by ag5493** [devopsfantasticfour/shopcarts#19]
**As a** developer
**I need** to GET shopping cart info
**So that** I can display on the API

**Assumptions:** 
*  Access to Mozilla extension 
https://addons.mozilla.org/en-US/firefox/addon/restclient/

**Acceptance Criteria:**
Can access GET/POST

Given 
- Local server
When 
- issue GET
Then 
- See HTTP response

**Comment by am7330** [comment]
I think there is also an extension that works for Chrome
