### ISSUE TITLE
David: Install Mozilla Extension

### ISSUE THREAD

**Issue by ag5493** [devopsfantasticfour/shopcarts#21]
As a developer
I need to GET shopping cart info
So that I can display on the API

Assumptions:

Access to Mozilla extension
https://addons.mozilla.org/en-US/firefox/addon/restclient/
Acceptance Criteria:
Can access GET/POST

Given

Local server
When
issue GET
Then
See HTTP response

**Comment by newgreg** [comment]
Need to find the chrome extension
