### ISSUE TITLE
Delete an item from shopping cart

### ISSUE THREAD

**Issue by newgreg** [devopsfantasticfour/shopcarts#27]
**As a** customer 
**I need** delete an item from the shopping  
**So that** I do not purchase items added by mistake or otherwise  

**Assumptions:** 
- Items added to the shopping cart can also be removed
- Customers can view the cart before purchase

**Acceptance Criteria:**
```
Given ...
When ...
Then ...
```

**Comment by aknain12** [comment]
Tested
