### ISSUE TITLE
Retrieve a shopping cart

### ISSUE THREAD

**Issue by aknain12** [devopsfantasticfour/shopcarts#31]
As a user
I need a way to retrieve the details of a particular shopping cart
So that I can conduct other operations such as add item or delete cart

Assumptions
The shopping cart details are stored and can be retrieved

Acceptance Criteria:
Given that the a particular shopping cart exist with id: 2 assigned to user with userId: 123
When I issue 'GET /carts/2'
Then the result should be:
a 200 return message showing successful request and the shopping cart details in following format:
{
"id": 2,
"userId": 123
}

**Comment by am7330** [comment]
tested by @aknain12 and @ag5493
