### ISSUE TITLE
Delete a shopping cart

### ISSUE THREAD

**Issue by aknain12** [devopsfantasticfour/shopcarts#32]
As a user
I need a way to delete a particular shopping cart
So that I can remove that shopping cart

Assumptions
This particular shopping cart exists

Acceptance Criteria:
Given that the a shopping cart with id: 5 exists in the database
When I issue 'DELETE /carts/5'
Then the shopping cart with id: 5 should be removed from the database & 204 header message should be returned on successful processing of request

**Comment by am7330** [comment]
tested by @am7330 and @ag5493
