### ISSUE TITLE
Update the quantity for one specific item in a shopping card

### ISSUE THREAD

**Issue by am7330** [devopsfantasticfour/shopcarts#38]
**As a** a user 
**I need** be able to modify the quantity of one item in the shopping card 
**So that** I can order the quantity that I want

**Assumptions:** 
- there is already the option to select the item 
- The shopping cart is created 
- There is a link between the shopping cart and the order 

**Acceptance Criteria:**
```
Given the shopping card 
When I change the quantity of item 
Then .it changes the quantity of item I have listed in my shopping card
```

**Comment by aknain12** [comment]
Tested & closed
