### ISSUE TITLE
Development Environment set up

### ISSUE THREAD

**Issue by ag5493** [devopsfantasticfour/shopcarts#4]
As a ...
Development team

I need ... 
development environment

So that ... 
we can develop code

Assumptions ....
Everyone has access to a laptop with 8 GB RAM

Acceptance Criteria
Ensure that all agile team members: 
- Have proper permissions to access GITHub organization, GIT repo, Zenhub
- Can modify code in the GIT repo, create a local branch, fetch new changes into local branch
- Have development environment to develop code

Given

When

Then

**Comment by aknain12** [comment]
Every team members can:
Have proper permissions to access GITHub organization, GIT repo, Zenhub
Can modify code in the GIT repo, create a local branch, fetch new changes into local branch
Have development environment to develop code

**Comment by aknain12** [comment]
Verified that every team members can do the required activities:
Have proper permissions to access GITHub organization, GIT repo, Zenhub
Can modify code in the GIT repo, create a local branch, fetch new changes into local branch
Have development environment to develop code
