### ISSUE TITLE
Andrea: Set up development environment

### ISSUE THREAD

**Issue by ag5493** [devopsfantasticfour/shopcarts#5]
As a ...
Development team member

I need ...
development environment

So that ...
we can develop code

Assumptions ....
Everyone has access to a laptop with 8 GB RAM

Acceptance Criteria
Ensure that Andrea has:

Have proper permissions to access GITHub organization, GIT repo, Zenhub
Can modify code in the GIT repo, create a local branch, fetch new changes into local branch
Have development environment to develop code

**Comment by am7330** [comment]
verify on Tuesday 5th with @ag5493 about the creation of the Branch

**Comment by am7330** [comment]
Done with setting up  the environment

**Comment by aknain12** [comment]
Verified that Andrea can access GITHub organization, GIT repo, Zenhub

**Comment by aknain12** [comment]
Andrea can access development environment to develop code

**Comment by aknain12** [comment]
Closed during sprint review
