### ISSUE TITLE
Check that everyone Travis CI is set up 

### ISSUE THREAD

**Issue by am7330** [devopsfantasticfour/shopcarts#51]
**As a** developer 
**I need** to have Travis CI set up 
**So that**  I can automate the integration of my pull requests

**Assumptions:** 
* everyone has already access to Travis CI

Acceptance Criteria:
Given all team members have created the account
When a pull request is raised
Then the test cases should run automatically and merges in the GIT repo

**Comment by aknain12** [comment]
All team members have access to Travis CI and with every pull request, the tests are run automatically and the code is merged with GIT repo.

**Comment by aknain12** [comment]
All team members have access to Travis CI
