### ISSUE TITLE
Create a .travis.yml file and configure Travis CI

### ISSUE THREAD

**Issue by am7330** [devopsfantasticfour/shopcarts#52]
**As a** developer
**I need** to create a .travis.yml file and to configure Travis CI to run test cases 
**So that**  my commit to master including that test case run are automated without manual intervention 

**Assumptions:** 
* every developer downloaded Travis CI

Acceptance Criteria 
Given all team members have access to Travis CI and have created & set up the account
When a pull request is raised
Then the test cases should run automatically and merges in the GIT repo

**Comment by aknain12** [comment]
Verified that Travis CI run all test cases every time pull request is created.
