### ISSUE TITLE
Add persistent storage to our application 

### ISSUE THREAD

**Issue by am7330** [devopsfantasticfour/shopcarts#57]
**As a** e-commerce customer 
**I need** to have a service with persistent storage 
**So that** I can access the modified shopping cart data across different sessions 

**Assumptions:** 
* Customer wants to access his/her shopping cart across sessions

Acceptance Criteria:
Given that A user has added an item or modified the cart details
When customer checks the cart in a new session
Then the cart should provide the last updated information

**Comment by aknain12** [comment]
Verified that the data is persistent across sessions
