### ISSUE TITLE
Modify models.py file to add persistence to model definition of resource.

### ISSUE THREAD

**Issue by newgreg** [devopsfantasticfour/shopcarts#58]
**As a developer 
**I need to modify my model.py file
**So that my models files connect to the POSTgreSQL

**Assumptions:** 
* Models.py with non-persistent storage is already in place

**Acceptance Criteria:**
```
Given the models.py file with connection to non-persistent storage
When I add the persistence to the model definition
Then the application should become persistent
```

**Comment by aknain12** [comment]
Verified and tested
