### ISSUE TITLE
Modify application to get the database credentials for PostgreSQL

### ISSUE THREAD

**Issue by am7330** [devopsfantasticfour/shopcarts#59]
**As a** developer
**I need** to pass database credentials to my application using the environment variable
**So that** the application can execute CRUD commands on the DB

**Assumptions:** 
* that the POSTgreSQL DB is setup in cloud and the DB credentials are stored in the environment variable

**Acceptance Criteria:**
```
Given the credentials to the DB are available in the environment variable
When the application tries to connect with the POSTgreSQL to CRUD
Then the application should be able to connect and work on the DB
```

**Comment by aknain12** [comment]
Verified that the application is able to pick the DB credentials from the env variable and connect to POSTgreSQL DB
