### ISSUE TITLE
David: Set up development environment

### ISSUE THREAD

**Issue by ag5493** [devopsfantasticfour/shopcarts#6]
As a ...
Development team member

I need ...
development environment

So that ...
we can develop code

Assumptions ....
Everyone has access to a laptop with 8 GB RAM

Acceptance Criteria
Ensure that Andrea has:

Have proper permissions to access GITHub organization, GIT repo, Zenhub
Can modify code in the GIT repo, create a local branch, fetch new changes into local branch
Have development environment to develop code

**Comment by aknain12** [comment]
Verified that David can access GITHub organization, GIT repo, Zenhub
David also has development environment to develop code

**Comment by aknain12** [comment]
Reviewed in the sprint review session and closed
