### ISSUE TITLE
Add persistence to Vagrantfile as a Docker container

### ISSUE THREAD

**Issue by newgreg** [devopsfantasticfour/shopcarts#60]
**As a developer  
**I need add the POSTgreSQL in Docker image
**So that ** no manual installation is required and it should automatically installed via VM vagrant

**Assumptions:** 
* vagrant file is avilable

**Acceptance Criteria:**
```
Given that POSTgreSQL is included in Docker image in vagrantfile
When we ssh into the image
Then we should be able to access the DB
```

**Comment by aknain12** [comment]
tested and verified that running vagrant ssh can connect to elephantsql
