### ISSUE TITLE
Bind the database service to the Cloud Foundry app

### ISSUE THREAD

**Issue by newgreg** [devopsfantasticfour/shopcarts#63]
**As a developer
**I need to bind the database service to the Cloud Foundry app
**So that our persistent data is stored in the cloud

**Assumptions:** 
* We are using Cloud Foundry, which is a container-based architecture. 

**Acceptance Criteria:**
Database is in the cloud 

Given postgres database service credentials
When asked to connect to the service
Then data will be stored in the ElephantSQL database and can be accessed by multiple users
```

**Comment by aknain12** [comment]
Verified and tested that database service is connected to the Cloud Foundry App
