### ISSUE TITLE
Create a database service for your Cloud Foundry app

### ISSUE THREAD

**Issue by am7330** [devopsfantasticfour/shopcarts#64]
**As a** developer 
**I need** to create a database service for your Cloud Foundry app
**So that** I can store my database in the cloud

**Assumptions:** 
* the integration of the app is persistent 

Accepytance Criteria:
Check in the IBM cloud and verify
If confused - Follow -> **Hamburger & Services**

**Comment by am7330** [comment]
Modifications of the assumption in the story

**Comment by aknain12** [comment]
Verified and tested that the DB service has been created in Cloud Foundry App
