### ISSUE TITLE
Download and install the IBM Cloud CLI in our vagrant VM

### ISSUE THREAD

**Issue by am7330** [devopsfantasticfour/shopcarts#67]
**As a** a developer 
**I need** to be able to use IBM Cloud CLI in our vagrant VM
**So that** developer can interact with IBM Cloud

**Assumptions:** 
* I need to have my VM up and working 

Acceptance Criteria:
Given that IBM cloud CLI has been added to vagrant VM
When the developer needs to connect to the IBM cloud through command line
Then developer successfully connects and operate on IBM cloud

**Comment by aknain12** [comment]
Verified and Tested
