### ISSUE TITLE
Create the necessary Cloud Foundry metadata files for deployment

### ISSUE THREAD

**Issue by am7330** [devopsfantasticfour/shopcarts#68]
**As a** developer
**I need** to create the necessary Cloud Foundry metadata files for deployment file
**So that** IBM Cloud will know how to deploy your application using these files

**Assumptions:** 
* we have setup IBM Cloud

**Acceptance Criteria:**
```
Given that these metadata files are created and available
When we deploy our application to IBM cloud
Then IBM cloud use the metadata files to deploy our application correctly
```

**Comment by aknain12** [comment]
Verified that IBM cloud deploys our application correctly
