### ISSUE TITLE
Amit: Set up development environment

### ISSUE THREAD

**Issue by ag5493** [devopsfantasticfour/shopcarts#7]
As a ...
Development team member

I need ...
development environment

So that ...
we can develop code

Assumptions ....
Everyone has access to a laptop with 8 GB RAM

Acceptance Criteria
Ensure that Andrea has:

Have proper permissions to access GITHub organization, GIT repo, Zenhub
Can modify code in the GIT repo, create a local branch, fetch new changes into local branch
Have development environment to develop code

**Comment by aknain12** [comment]
Can access GITHub organization, GIT repo, Zenhub.
Also can modify code in the GIT repo, create a local branch, fetch new changes into local branch

**Comment by newgreg** [comment]
Verified and closed
