### ISSUE TITLE
Create a simple single page UI 

### ISSUE THREAD

**Issue by am7330** [devopsfantasticfour/shopcarts#75]
**As a** shopping addict 
**I need** to have a pretty page 
**So that** I can have a clear understanding of the items I added in my shopcart

**Assumptions:** 
* The developer has to create the UI before adding behavioral testing because the BDD tests will only be testing the application from the UI
* Developer will use Selenium

**Acceptance Criteria:**
```
Given a shopping addict
When he/she wants to use the option shop cart
Then he will have a pretty view of his shop cart without having to know any code
```

**Comment by aknain12** [comment]
Created and checked the single page UI
