### ISSUE TITLE
 Adding BDD automated testing for the UI

### ISSUE THREAD

**Issue by am7330** [devopsfantasticfour/shopcarts#76]
**As a** developer
**I need** to automate the BDD testing
**So that** developers can run tests automatically and these tests are understood by Business and technical people

**Assumptions:** 
* BDD testing allows to describe the behavior of the system from the outside in 
* and is used for integration and acceptance testing
* Business people have an understanding of the test running 

**Acceptance Criteria:**
```
Given the UI shopcart
When a new story is made
Then a BDD test should be automatically run
```

**Comment by aknain12** [comment]
Confirmed that the BDD automated testing is working fine.
