### ISSUE TITLE
Create a BDD shopcarts.feature file 

### ISSUE THREAD

**Issue by am7330** [devopsfantasticfour/shopcarts#77]
**As a** developer 
**I need** a shopcarts.feature file 
**So that** Behave will be able to find the folder when BDD test will be launched. 

**Assumptions:** 
* BDD test will be implemented in our shopcarts
* Developers will use Gherkin syntax

**Acceptance Criteria:**
```
Given BDD test are implemented 
When Behave will start 
Then it will find the .feature file
`

**Comment by aknain12** [comment]
Confirmed and checked the .feature file
