### ISSUE TITLE
Create shopcarts.steps file 

### ISSUE THREAD

**Issue by am7330** [devopsfantasticfour/shopcarts#78]
**As a** developer
**I need** to create a shopcarts.steps file 
**So that** I can test my RESTful API from the outside in

**Assumptions:** 
* I have a  BDD shopcarts.feature file already created

**Acceptance Criteria:**
```
Given a BDD test
When it will be automatically launch
Then it will detect the Given, When and Then
```

**Comment by aknain12** [comment]
Confirmed .steps file is created and working
