### ISSUE TITLE
Add 7 actions Create, Read, Update, Delete, List, Query, and Action in feature file

### ISSUE THREAD

**Issue by am7330** [devopsfantasticfour/shopcarts#80]
**As a** developer
**I need** to be able to test the 7 following actions : Create, Read, Update, Delete, List, Query, and Action
**So that** Shopcarts UI will be fully testable 

**Assumptions:** 
* the file shopcarts.features was created
* will be written in Gerkin

**Acceptance Criteria:**
```
Given shopcarts UI
When a developer wants to develop a new enhancement, 
Then the stories will be automatically tested
```

**Comment by aknain12** [comment]
Confirmed that all 7 actions are added and working in feature file
