### ISSUE TITLE
Test to make sure Update scenario in feature file is working

### ISSUE THREAD

**Issue by newgreg** [devopsfantasticfour/shopcarts#81]
**As a** developer 
**I need to** run tests for the update scenario...  
**So that** I know the test is fully working...  

**Assumptions:** 
* The Shopcarts UI was created
* BDD is written in Gerkin

**Acceptance Criteria:**
```
Given the story
When using update
Then behave command will be successful and scenarios will be all green
```

**Comment by aknain12** [comment]
Tested and confirmed that update scenario is working
