### ISSUE TITLE
Test to make sure Delete scenario in feature file is working

### ISSUE THREAD

**Issue by am7330** [devopsfantasticfour/shopcarts#84]
As a developer
I need to run tests for the Delete scenario...
So that I know the test is fully working...

**Assumptions:** 
* The Shopcarts UI was created
* BDD is written in Gerkin

**Acceptance Criteria:**
```
Given the story
When using delete
Then behave command will be successful and scenarios will be all green
```

**Comment by aknain12** [comment]
Tested and confirmed that delete scenario is working
