### ISSUE TITLE
Test to make sure Action scenario in feature file is working

### ISSUE THREAD

**Issue by newgreg** [devopsfantasticfour/shopcarts#85]
**As a** developer 
**I need to** run tests for the Action scenario...  
**So that** I know the test is fully working...  

**Assumptions:** 
* The Shopcarts UI was created
* BDD is written in Gerkin

**Acceptance Criteria:**
```
Given the story
When using Action
Then behave command will be successful and scenarios will be all green
```

**Comment by aknain12** [comment]
Tested and confirmed that query scenario is working
