### ISSUE TITLE
Test to make sure Query scenario in feature file is working

### ISSUE THREAD

**Issue by am7330** [devopsfantasticfour/shopcarts#86]
**As a** developer 
**I need to** run tests for the query scenario...  
**So that** I know the test is fully working...  

**Assumptions:** 
* The Shopcarts UI was created
* BDD is written in Gerkin

**Acceptance Criteria:**
```
Given the story
When using query
Then behave command will be successful and scenarios will be all green
```

**Comment by aknain12** [comment]
Tested and confirmed that query scenario is working.
