### ISSUE TITLE
Test to make sure Read scenario in feature file is working

### ISSUE THREAD

**Issue by am7330** [devopsfantasticfour/shopcarts#87]
**As a** developer 
**I need to** run tests for the read scenario...  
**So that** I know the test is fully working...  

**Assumptions:** 
* The Shopcarts UI was created
* BDD is written in Gerkin

**Acceptance Criteria:**
```
Given the story
When using Read
Then behave command will be successful and scenarios will be all green
```

**Comment by aknain12** [comment]
Tested and confirmed that read scenario is working
